### ISSUE TITLE
Update error for multiple primary keys tables

### ISSUE THREAD

**Issue by georgeenaru** [Mimetis/SyncWinRT#16]
Hi,

Thanks for this toolkit, it works fine, except one issue.
When trying to sync tables that have more than one primary keys the "SyncAsync" method throws an error. Below is the error.
To get over it I had to change all my tables with multiple keys to use only one primary key each and it worked.

Error occured during Upload request.
System.ArgumentException
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Synchronization.Services.RequestParser.ReadIncomingRequestStreamForPost()
   at Microsoft.Synchronization.Services.RequestParser.ParseIncomingRequest()
   at Microsoft.Synchronization.Services.SyncService`1.ProcessRequestForMessage(Stream messageBody)

**Comment by vikingau** [comment]
Hi George, 
If you mean that the table has more than one table in the primary key, then I have already submitted a patch that will allow for a multiple column primary key.
Please review other pull requests
